kind: Template
apiVersion: v1
parameters:
  - name: OUTPUT_TAG
    required: true
    default: dev
    description: the output image tag
objects:
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    spec:
      failedBuildsHistoryLimit: 5
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: 'ocp101-demo:${OUTPUT_TAG}'
      postCommit: {}
      resources: {}
      runPolicy: Serial
      source:
        contextDir: api
        git:
          uri: 'https://github.com/patricksimonian/ocp101-demo'
        type: Git
      strategy:
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: 'nodejs:10'
            namespace: openshift
        type: Source
      successfulBuildsHistoryLimit: 5
      triggers:
        - github:
            secret: ULEVoQqv-ZVwEk3JHOKv
          type: GitHub
        - generic:
            secret: lzJAAYPvTe2DGG5AhJPS
          type: Generic
        - type: ConfigChange
        - imageChange:
            lastTriggeredImageID: >-
              docker-registry.default.svc:5000/openshift/nodejs@sha256:91002d434b585df0262f0350fe91dac9adb3e56d6b9ccfea47ac91064f4513b7
          type: ImageChange
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewBuild
      labels:
        build: ocp101-demo
        app: ocp101-demo
        version: ${OUTPUT_TAG}
      name: ocp101-demo
