apiVersion: v1
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    labels:
      build: ${NAME}
    name: ${NAME}
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    labels:
      build: ${NAME}
    name: ${NAME}
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: ${IMAGE_NAME}:${IMAGE_TAG}
    postCommit: {}
    resources: {}
    source:
      contextDir: api
      git:
        ref: ${GIT_BRANCH}
        uri: https://github.com/patricksimonian/${NAME}
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: nodejs:12
          namespace: openshift
      type: Source
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
kind: Template
parameters:
- name: NAME
  value: ocp101-demo
  description: Name of the infrastructure
- name: IMAGE_TAG
  value: dev
  description: the output image tag for ocp101 demo 
- name: IMAGE_NAME
  value: ocp101-demo
  description: the output image tag for ocp101 demo 
- name: GIT_BRANCH
  value: master
  description: the git branch to build off of
metadata: {}
